//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Address : Record<Address>
    {
            public readonly string CountryCode;
            public readonly Field Field;
            public readonly string Line1;
            public readonly string Line2;
            public readonly string Locality;
            public readonly string PostalCode;
            public readonly string Region;
            public readonly string ZipCode;
            public readonly string ZipFour;
      
      public Address(string countryCode = default, Field field = default, string line1 = default, string line2 = default, string locality = default, string postalCode = default, string region = default, string zipCode = default, string zipFour = default)
      {
                CountryCode = countryCode;
                Field = field;
                Line1 = line1;
                Line2 = line2;
                Locality = locality;
                PostalCode = postalCode;
                Region = region;
                ZipCode = zipCode;
                ZipFour = zipFour;
        
      }

      public Address Copy(string countryCode = default, Field field = default, string line1 = default, string line2 = default, string locality = default, string postalCode = default, string region = default, string zipCode = default, string zipFour = default) => new Address(
                  countryCode:  countryCode ?? CountryCode, 
                        field:  field == default ? Field : field, 
                        line1:  line1 ?? Line1, 
                        line2:  line2 ?? Line2, 
                        locality:  locality ?? Locality, 
                        postalCode:  postalCode ?? PostalCode, 
                        region:  region ?? Region, 
                        zipCode:  zipCode ?? ZipCode, 
                        zipFour:  zipFour ?? ZipFour
            
      );
    }
}