//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Appointment : Record<Appointment>
    {
            public readonly long ContactId;
            public readonly string Description;
            public readonly string EndDate;
            public readonly string Location;
            public readonly int RemindTime;
            public readonly string StartDate;
            public readonly string Title;
            public readonly long User;
      
      public Appointment(long contactId = default, string description = default, string endDate = default, string location = default, int remindTime = default, string startDate = default, string title = default, long user = default)
      {
                ContactId = contactId;
                Description = description;
                EndDate = endDate;
                Location = location;
                RemindTime = remindTime;
                StartDate = startDate;
                Title = title;
                User = user;
        
      }

      public Appointment Copy(long? contactId = default, string description = default, string endDate = default, string location = default, int? remindTime = default, string startDate = default, string title = default, long? user = default) => new Appointment(
                  contactId:  contactId ?? ContactId, 
                        description:  description ?? Description, 
                        endDate:  endDate ?? EndDate, 
                        location:  location ?? Location, 
                        remindTime:  remindTime ?? RemindTime, 
                        startDate:  startDate ?? StartDate, 
                        title:  title ?? Title, 
                        user:  user ?? User
            
      );
    }
}