//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class AppointmentList : Record<AppointmentList>
    {
            public readonly Lst<Appointment> Appointments;
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
            public readonly string SyncToken;
      
      public AppointmentList(Lst<Appointment> appointments = default, int count = default, string next = default, string previous = default, string syncToken = default)
      {
                Appointments = appointments;
                Count = count;
                Next = next;
                Previous = previous;
                SyncToken = syncToken;
        
      }

      public AppointmentList Copy(Lst<Appointment> appointments = default, int? count = default, string next = default, string previous = default, string syncToken = default) => new AppointmentList(
                  appointments:  appointments == default ? Appointments : appointments, 
                        count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous, 
                        syncToken:  syncToken ?? SyncToken
            
      );
    }
}