//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class BasicContact : Record<BasicContact>
    {
            public readonly string Email;
            public readonly string FirstName;
            public readonly long Id;
            public readonly string LastName;
      
      public BasicContact(string email = default, string firstName = default, long id = default, string lastName = default)
      {
                Email = email;
                FirstName = firstName;
                Id = id;
                LastName = lastName;
        
      }

      public BasicContact Copy(string email = default, string firstName = default, long? id = default, string lastName = default) => new BasicContact(
                  email:  email ?? Email, 
                        firstName:  firstName ?? FirstName, 
                        id:  id ?? Id, 
                        lastName:  lastName ?? LastName
            
      );
    }
}