//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CampaignList : Record<CampaignList>
    {
            public readonly Lst<Campaign> Campaigns;
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
      
      public CampaignList(Lst<Campaign> campaigns = default, int count = default, string next = default, string previous = default)
      {
                Campaigns = campaigns;
                Count = count;
                Next = next;
                Previous = previous;
        
      }

      public CampaignList Copy(Lst<Campaign> campaigns = default, int? count = default, string next = default, string previous = default) => new CampaignList(
                  campaigns:  campaigns == default ? Campaigns : campaigns, 
                        count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous
            
      );
    }
}