//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Campaign : Record<Campaign>
    {
            public readonly int ActiveContactCount;
            public readonly int CompletedContactCount;
            public readonly long CreatedByGlobalId;
            public readonly string DateCreated;
            public readonly string ErrorMessage;
            public readonly Lst<Goal> Goals;
            public readonly long Id;
            public readonly bool Locked;
            public readonly string Name;
            public readonly string PublishedDate;
            public readonly bool PublishedStatus;
            public readonly string PublishedTimeZone;
            public readonly Lst<Sequence> Sequences;
            public readonly string TimeZone;
      
      public Campaign(int activeContactCount = default, int completedContactCount = default, long createdByGlobalId = default, string dateCreated = default, string errorMessage = default, Lst<Goal> goals = default, long id = default, bool locked = default, string name = default, string publishedDate = default, bool publishedStatus = default, string publishedTimeZone = default, Lst<Sequence> sequences = default, string timeZone = default)
      {
                ActiveContactCount = activeContactCount;
                CompletedContactCount = completedContactCount;
                CreatedByGlobalId = createdByGlobalId;
                DateCreated = dateCreated;
                ErrorMessage = errorMessage;
                Goals = goals;
                Id = id;
                Locked = locked;
                Name = name;
                PublishedDate = publishedDate;
                PublishedStatus = publishedStatus;
                PublishedTimeZone = publishedTimeZone;
                Sequences = sequences;
                TimeZone = timeZone;
        
      }

      public Campaign Copy(int? activeContactCount = default, int? completedContactCount = default, long? createdByGlobalId = default, string dateCreated = default, string errorMessage = default, Lst<Goal> goals = default, long? id = default, bool locked = default, string name = default, string publishedDate = default, bool publishedStatus = default, string publishedTimeZone = default, Lst<Sequence> sequences = default, string timeZone = default) => new Campaign(
                  activeContactCount:  activeContactCount ?? ActiveContactCount, 
                        completedContactCount:  completedContactCount ?? CompletedContactCount, 
                        createdByGlobalId:  createdByGlobalId ?? CreatedByGlobalId, 
                        dateCreated:  dateCreated ?? DateCreated, 
                        errorMessage:  errorMessage ?? ErrorMessage, 
                        goals:  goals == default ? Goals : goals, 
                        id:  id ?? Id, 
                        locked:  locked == default ? Locked : locked, 
                        name:  name ?? Name, 
                        publishedDate:  publishedDate ?? PublishedDate, 
                        publishedStatus:  publishedStatus == default ? PublishedStatus : publishedStatus, 
                        publishedTimeZone:  publishedTimeZone ?? PublishedTimeZone, 
                        sequences:  sequences == default ? Sequences : sequences, 
                        timeZone:  timeZone ?? TimeZone
            
      );
    }
}