//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CampaignLandingPageNodeDTO : Record<CampaignLandingPageNodeDTO>
    {
            public readonly string FormId;
            public readonly string Id;
            public readonly string LandingPageId;
            public readonly Lst<string> LeadBucketIds;
            public readonly string Name;
            public readonly object Properties;
            public readonly bool Ready;
            public readonly Type Type;
      
      public CampaignLandingPageNodeDTO(string formId = default, string id = default, string landingPageId = default, Lst<string> leadBucketIds = default, string name = default, object properties = default, bool ready = default, Type type = default)
      {
                FormId = formId;
                Id = id;
                LandingPageId = landingPageId;
                LeadBucketIds = leadBucketIds;
                Name = name;
                Properties = properties;
                Ready = ready;
                Type = type;
        
      }

      public CampaignLandingPageNodeDTO Copy(string formId = default, string id = default, string landingPageId = default, Lst<string> leadBucketIds = default, string name = default, object properties = default, bool ready = default, Type type = default) => new CampaignLandingPageNodeDTO(
                  formId:  formId ?? FormId, 
                        id:  id ?? Id, 
                        landingPageId:  landingPageId ?? LandingPageId, 
                        leadBucketIds:  leadBucketIds == default ? LeadBucketIds : leadBucketIds, 
                        name:  name ?? Name, 
                        properties:  properties ?? Properties, 
                        ready:  ready == default ? Ready : ready, 
                        type:  type == default ? Type : type
            
      );
    }
}