//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CategoryReference : Record<CategoryReference>
    {
            public readonly long Id;
      
      public CategoryReference(long id = default)
      {
                Id = id;
        
      }

      public CategoryReference Copy(long? id = default) => new CategoryReference(
                  id:  id ?? Id
            
      );
    }
}