//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CheckListItemDetails : Record<CheckListItemDetails>
    {
            public readonly string Description;
            public readonly string DoneDate;
            public readonly long Id;
            public readonly long InstanceId;
            public readonly int ItemOrder;
            public readonly bool Required;
      
      public CheckListItemDetails(string description = default, string doneDate = default, long id = default, long instanceId = default, int itemOrder = default, bool required = default)
      {
                Description = description;
                DoneDate = doneDate;
                Id = id;
                InstanceId = instanceId;
                ItemOrder = itemOrder;
                Required = required;
        
      }

      public CheckListItemDetails Copy(string description = default, string doneDate = default, long? id = default, long? instanceId = default, int? itemOrder = default, bool required = default) => new CheckListItemDetails(
                  description:  description ?? Description, 
                        doneDate:  doneDate ?? DoneDate, 
                        id:  id ?? Id, 
                        instanceId:  instanceId ?? InstanceId, 
                        itemOrder:  itemOrder ?? ItemOrder, 
                        required:  required == default ? Required : required
            
      );
    }
}