//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CompanyList : Record<CompanyList>
    {
            public readonly Lst<Company> Companies;
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
      
      public CompanyList(Lst<Company> companies = default, int count = default, string next = default, string previous = default)
      {
                Companies = companies;
                Count = count;
                Next = next;
                Previous = previous;
        
      }

      public CompanyList Copy(Lst<Company> companies = default, int? count = default, string next = default, string previous = default) => new CompanyList(
                  companies:  companies == default ? Companies : companies, 
                        count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous
            
      );
    }
}