//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CompanyReference : Record<CompanyReference>
    {
            public readonly string CompanyName;
            public readonly long Id;
      
      public CompanyReference(string companyName = default, long id = default)
      {
                CompanyName = companyName;
                Id = id;
        
      }

      public CompanyReference Copy(string companyName = default, long? id = default) => new CompanyReference(
                  companyName:  companyName ?? CompanyName, 
                        id:  id ?? Id
            
      );
    }
}