//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CompanyPhoneNumber : Record<CompanyPhoneNumber>
    {
            public readonly string Extension;
            public readonly string Number;
            public readonly string Type;
      
      public CompanyPhoneNumber(string extension = default, string number = default, string type = default)
      {
                Extension = extension;
                Number = number;
                Type = type;
        
      }

      public CompanyPhoneNumber Copy(string extension = default, string number = default, string type = default) => new CompanyPhoneNumber(
                  extension:  extension ?? Extension, 
                        number:  number ?? Number, 
                        type:  type ?? Type
            
      );
    }
}