//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Company : Record<Company>
    {
            public readonly CompanyAddress Address;
            public readonly string CompanyName;
            public readonly Lst<CustomFieldValue> CustomFields;
            public readonly string EmailAddress;
            public readonly bool EmailOptedIn;
            public readonly EmailStatus EmailStatus;
            public readonly CompanyFaxNumber FaxNumber;
            public readonly long Id;
            public readonly string Notes;
            public readonly CompanyPhoneNumber PhoneNumber;
            public readonly string Website;
      
      public Company(CompanyAddress address = default, string companyName = default, Lst<CustomFieldValue> customFields = default, string emailAddress = default, bool emailOptedIn = default, EmailStatus emailStatus = default, CompanyFaxNumber faxNumber = default, long id = default, string notes = default, CompanyPhoneNumber phoneNumber = default, string website = default)
      {
                Address = address;
                CompanyName = companyName;
                CustomFields = customFields;
                EmailAddress = emailAddress;
                EmailOptedIn = emailOptedIn;
                EmailStatus = emailStatus;
                FaxNumber = faxNumber;
                Id = id;
                Notes = notes;
                PhoneNumber = phoneNumber;
                Website = website;
        
      }

      public Company Copy(CompanyAddress address = default, string companyName = default, Lst<CustomFieldValue> customFields = default, string emailAddress = default, bool emailOptedIn = default, EmailStatus emailStatus = default, CompanyFaxNumber faxNumber = default, long? id = default, string notes = default, CompanyPhoneNumber phoneNumber = default, string website = default) => new Company(
                  address:  address == default ? Address : address, 
                        companyName:  companyName ?? CompanyName, 
                        customFields:  customFields == default ? CustomFields : customFields, 
                        emailAddress:  emailAddress ?? EmailAddress, 
                        emailOptedIn:  emailOptedIn == default ? EmailOptedIn : emailOptedIn, 
                        emailStatus:  emailStatus == default ? EmailStatus : emailStatus, 
                        faxNumber:  faxNumber == default ? FaxNumber : faxNumber, 
                        id:  id ?? Id, 
                        notes:  notes ?? Notes, 
                        phoneNumber:  phoneNumber == default ? PhoneNumber : phoneNumber, 
                        website:  website ?? Website
            
      );
    }
}