//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CompanyFaxNumber : Record<CompanyFaxNumber>
    {
            public readonly string Number;
            public readonly string Type;
      
      public CompanyFaxNumber(string number = default, string type = default)
      {
                Number = number;
                Type = type;
        
      }

      public CompanyFaxNumber Copy(string number = default, string type = default) => new CompanyFaxNumber(
                  number:  number ?? Number, 
                        type:  type ?? Type
            
      );
    }
}