//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class ContactList : Record<ContactList>
    {
            public readonly Lst<FullContact> Contacts;
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
      
      public ContactList(Lst<FullContact> contacts = default, int count = default, string next = default, string previous = default)
      {
                Contacts = contacts;
                Count = count;
                Next = next;
                Previous = previous;
        
      }

      public ContactList Copy(Lst<FullContact> contacts = default, int? count = default, string next = default, string previous = default) => new ContactList(
                  contacts:  contacts == default ? Contacts : contacts, 
                        count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous
            
      );
    }
}