//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class ContactTag : Record<ContactTag>
    {
            public readonly string DateApplied;
            public readonly SimpleTag Tag;
      
      public ContactTag(string dateApplied = default, SimpleTag tag = default)
      {
                DateApplied = dateApplied;
                Tag = tag;
        
      }

      public ContactTag Copy(string dateApplied = default, SimpleTag tag = default) => new ContactTag(
                  dateApplied:  dateApplied ?? DateApplied, 
                        tag:  tag == default ? Tag : tag
            
      );
    }
}