//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CreateCompany : Record<CreateCompany>
    {
            public readonly CompanyAddress Address;
            public readonly string CompanyName;
            public readonly Lst<CustomFieldValue> CustomFields;
            public readonly string EmailAddress;
            public readonly CompanyFaxNumber FaxNumber;
            public readonly string Notes;
            public readonly string OptInReason;
            public readonly CompanyPhoneNumber PhoneNumber;
            public readonly string Website;
      
      public CreateCompany(CompanyAddress address = default, string companyName = default, Lst<CustomFieldValue> customFields = default, string emailAddress = default, CompanyFaxNumber faxNumber = default, string notes = default, string optInReason = default, CompanyPhoneNumber phoneNumber = default, string website = default)
      {
                Address = address;
                CompanyName = companyName;
                CustomFields = customFields;
                EmailAddress = emailAddress;
                FaxNumber = faxNumber;
                Notes = notes;
                OptInReason = optInReason;
                PhoneNumber = phoneNumber;
                Website = website;
        
      }

      public CreateCompany Copy(CompanyAddress address = default, string companyName = default, Lst<CustomFieldValue> customFields = default, string emailAddress = default, CompanyFaxNumber faxNumber = default, string notes = default, string optInReason = default, CompanyPhoneNumber phoneNumber = default, string website = default) => new CreateCompany(
                  address:  address == default ? Address : address, 
                        companyName:  companyName ?? CompanyName, 
                        customFields:  customFields == default ? CustomFields : customFields, 
                        emailAddress:  emailAddress ?? EmailAddress, 
                        faxNumber:  faxNumber == default ? FaxNumber : faxNumber, 
                        notes:  notes ?? Notes, 
                        optInReason:  optInReason ?? OptInReason, 
                        phoneNumber:  phoneNumber == default ? PhoneNumber : phoneNumber, 
                        website:  website ?? Website
            
      );
    }
}