//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CreateTag : Record<CreateTag>
    {
            public readonly CategoryReference Category;
            public readonly string Description;
            public readonly string Name;
      
      public CreateTag(CategoryReference category = default, string description = default, string name = default)
      {
                Category = category;
                Description = description;
                Name = name;
        
      }

      public CreateTag Copy(CategoryReference category = default, string description = default, string name = default) => new CreateTag(
                  category:  category == default ? Category : category, 
                        description:  description ?? Description, 
                        name:  name ?? Name
            
      );
    }
}