//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CreateTagCategory : Record<CreateTagCategory>
    {
            public readonly string Description;
            public readonly string Name;
      
      public CreateTagCategory(string description = default, string name = default)
      {
                Description = description;
                Name = name;
        
      }

      public CreateTagCategory Copy(string description = default, string name = default) => new CreateTagCategory(
                  description:  description ?? Description, 
                        name:  name ?? Name
            
      );
    }
}