//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CreditCard : Record<CreditCard>
    {
            public readonly Address Address;
            public readonly string CardNumber;
            public readonly string CardType;
            public readonly string EmailAddress;
            public readonly string ExpirationMonth;
            public readonly string ExpirationYear;
            public readonly string MaestroIssueNumber;
            public readonly string MaestroStartDateMonth;
            public readonly string MaestroStartDateYear;
            public readonly string NameOnCard;
            public readonly string VerificationCode;
      
      public CreditCard(Address address = default, string cardNumber = default, string cardType = default, string emailAddress = default, string expirationMonth = default, string expirationYear = default, string maestroIssueNumber = default, string maestroStartDateMonth = default, string maestroStartDateYear = default, string nameOnCard = default, string verificationCode = default)
      {
                Address = address;
                CardNumber = cardNumber;
                CardType = cardType;
                EmailAddress = emailAddress;
                ExpirationMonth = expirationMonth;
                ExpirationYear = expirationYear;
                MaestroIssueNumber = maestroIssueNumber;
                MaestroStartDateMonth = maestroStartDateMonth;
                MaestroStartDateYear = maestroStartDateYear;
                NameOnCard = nameOnCard;
                VerificationCode = verificationCode;
        
      }

      public CreditCard Copy(Address address = default, string cardNumber = default, string cardType = default, string emailAddress = default, string expirationMonth = default, string expirationYear = default, string maestroIssueNumber = default, string maestroStartDateMonth = default, string maestroStartDateYear = default, string nameOnCard = default, string verificationCode = default) => new CreditCard(
                  address:  address == default ? Address : address, 
                        cardNumber:  cardNumber ?? CardNumber, 
                        cardType:  cardType ?? CardType, 
                        emailAddress:  emailAddress ?? EmailAddress, 
                        expirationMonth:  expirationMonth ?? ExpirationMonth, 
                        expirationYear:  expirationYear ?? ExpirationYear, 
                        maestroIssueNumber:  maestroIssueNumber ?? MaestroIssueNumber, 
                        maestroStartDateMonth:  maestroStartDateMonth ?? MaestroStartDateMonth, 
                        maestroStartDateYear:  maestroStartDateYear ?? MaestroStartDateYear, 
                        nameOnCard:  nameOnCard ?? NameOnCard, 
                        verificationCode:  verificationCode ?? VerificationCode
            
      );
    }
}