//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CustomFieldValue : Record<CustomFieldValue>
    {
            public readonly object Content;
            public readonly long Id;
      
      public CustomFieldValue(object content = default, long id = default)
      {
                Content = content;
                Id = id;
        
      }

      public CustomFieldValue Copy(object content = default, long? id = default) => new CustomFieldValue(
                  content:  content ?? Content, 
                        id:  id ?? Id
            
      );
    }
}