//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CustomFieldOption : Record<CustomFieldOption>
    {
            public readonly string Id;
            public readonly string Label;
            public readonly Lst<CustomFieldOption> Options;
      
      public CustomFieldOption(string id = default, string label = default, Lst<CustomFieldOption> options = default)
      {
                Id = id;
                Label = label;
                Options = options;
        
      }

      public CustomFieldOption Copy(string id = default, string label = default, Lst<CustomFieldOption> options = default) => new CustomFieldOption(
                  id:  id ?? Id, 
                        label:  label ?? Label, 
                        options:  options == default ? Options : options
            
      );
    }
}