//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class CustomFieldMetaData : Record<CustomFieldMetaData>
    {
            public readonly FieldType FieldType;
            public readonly long Id;
            public readonly string Label;
            public readonly Lst<CustomFieldOption> Options;
            public readonly RecordType RecordType;
      
      public CustomFieldMetaData(FieldType fieldType = default, long id = default, string label = default, Lst<CustomFieldOption> options = default, RecordType recordType = default)
      {
                FieldType = fieldType;
                Id = id;
                Label = label;
                Options = options;
                RecordType = recordType;
        
      }

      public CustomFieldMetaData Copy(FieldType fieldType = default, long? id = default, string label = default, Lst<CustomFieldOption> options = default, RecordType recordType = default) => new CustomFieldMetaData(
                  fieldType:  fieldType == default ? FieldType : fieldType, 
                        id:  id ?? Id, 
                        label:  label ?? Label, 
                        options:  options == default ? Options : options, 
                        recordType:  recordType == default ? RecordType : recordType
            
      );
    }
}