//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class EmailSentQueryResultList : Record<EmailSentQueryResultList>
    {
            public readonly int Count;
            public readonly Lst<EmailSentQueryResult> Emails;
            public readonly string Next;
            public readonly string Previous;
      
      public EmailSentQueryResultList(int count = default, Lst<EmailSentQueryResult> emails = default, string next = default, string previous = default)
      {
                Count = count;
                Emails = emails;
                Next = next;
                Previous = previous;
        
      }

      public EmailSentQueryResultList Copy(int? count = default, Lst<EmailSentQueryResult> emails = default, string next = default, string previous = default) => new EmailSentQueryResultList(
                  count:  count ?? Count, 
                        emails:  emails == default ? Emails : emails, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous
            
      );
    }
}