//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class EmailAddress : Record<EmailAddress>
    {
            public readonly string Email;
            public readonly Field Field;
      
      public EmailAddress(string email = default, Field field = default)
      {
                Email = email;
                Field = field;
        
      }

      public EmailAddress Copy(string email = default, Field field = default) => new EmailAddress(
                  email:  email ?? Email, 
                        field:  field == default ? Field : field
            
      );
    }
}