//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class EmailSentCreateList : Record<EmailSentCreateList>
    {
            public readonly Lst<EmailSentCreate> Emails;
      
      public EmailSentCreateList(Lst<EmailSentCreate> emails = default)
      {
                Emails = emails;
        
      }

      public EmailSentCreateList Copy(Lst<EmailSentCreate> emails = default) => new EmailSentCreateList(
                  emails:  emails == default ? Emails : emails
            
      );
    }
}