//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum EmailStatus
  { 
    [EnumMember(Value = "Unengaged Marketable")]
    Unengagedmarketable,
    
    [EnumMember(Value = "Unconfirmed")]
    Unconfirmed,
    
    [EnumMember(Value = "Confirmed (Legacy)")]
    Confirmedlegacy,
    
    [EnumMember(Value = "Confirmed")]
    Confirmed,
    
    [EnumMember(Value = "Unengaged NonMarketable")]
    Unengagednonmarketable,
    
    [EnumMember(Value = "Non-marketable")]
    Nonmarketable,
    
    [EnumMember(Value = "Lockdown")]
    Lockdown,
    
    [EnumMember(Value = "Soft Bounce")]
    Softbounce,
    
    [EnumMember(Value = "Hard Bounce")]
    Hardbounce,
    
    [EnumMember(Value = "Opt-Out")]
    Optout,
    
    [EnumMember(Value = "Opt-Out: Admin")]
    Optoutadmin,
    
    [EnumMember(Value = "Opt-Out: System")]
    Optoutsystem,
    
    [EnumMember(Value = "List Unsubscribe")]
    Listunsubscribe,
    
    [EnumMember(Value = "Provided Feedback")]
    Providedfeedback,
    
    [EnumMember(Value = "Reported Spam")]
    Reportedspam,
    
    [EnumMember(Value = "Invalid Email")]
    Invalidemail
      }
}