//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class EntryLongString : Record<EntryLongString>
    {
            public readonly Key Key;
      
      public EntryLongString(Key key = default)
      {
                Key = key;
        
      }

      public EntryLongString Copy(Key key = default) => new EntryLongString(
                  key:  key == default ? Key : key
            
      );
    }
}