//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class FaxNumber : Record<FaxNumber>
    {
            public readonly Field Field;
            public readonly string Number;
            public readonly string Type;
      
      public FaxNumber(Field field = default, string number = default, string type = default)
      {
                Field = field;
                Number = number;
                Type = type;
        
      }

      public FaxNumber Copy(Field field = default, string number = default, string type = default) => new FaxNumber(
                  field:  field == default ? Field : field, 
                        number:  number ?? Number, 
                        type:  type ?? Type
            
      );
    }
}