//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum FieldType
  { 
    [EnumMember(Value = "Currency")]
    Currency,
    
    [EnumMember(Value = "Date")]
    Date,
    
    [EnumMember(Value = "DateTime")]
    Datetime,
    
    [EnumMember(Value = "DayOfWeek")]
    Dayofweek,
    
    [EnumMember(Value = "Drilldown")]
    Drilldown,
    
    [EnumMember(Value = "Email")]
    Email,
    
    [EnumMember(Value = "Month")]
    Month,
    
    [EnumMember(Value = "ListBox")]
    Listbox,
    
    [EnumMember(Value = "Name")]
    Name,
    
    [EnumMember(Value = "WholeNumber")]
    Wholenumber,
    
    [EnumMember(Value = "DecimalNumber")]
    Decimalnumber,
    
    [EnumMember(Value = "Percent")]
    Percent,
    
    [EnumMember(Value = "PhoneNumber")]
    Phonenumber,
    
    [EnumMember(Value = "Radio")]
    Radio,
    
    [EnumMember(Value = "Dropdown")]
    Dropdown,
    
    [EnumMember(Value = "SocialSecurityNumber")]
    Socialsecuritynumber,
    
    [EnumMember(Value = "State")]
    State,
    
    [EnumMember(Value = "Text")]
    Text,
    
    [EnumMember(Value = "TextArea")]
    Textarea,
    
    [EnumMember(Value = "User")]
    User,
    
    [EnumMember(Value = "UserListBox")]
    Userlistbox,
    
    [EnumMember(Value = "Website")]
    Website,
    
    [EnumMember(Value = "Year")]
    Year,
    
    [EnumMember(Value = "YesNo")]
    Yesno
      }
}