//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum Field
  { 
    [EnumMember(Value = "PHONE1")]
    Phone1,
    
    [EnumMember(Value = "PHONE2")]
    Phone2,
    
    [EnumMember(Value = "PHONE3")]
    Phone3,
    
    [EnumMember(Value = "PHONE4")]
    Phone4,
    
    [EnumMember(Value = "PHONE5")]
    Phone5
      }
}