//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class FileUpload : Record<FileUpload>
    {
            public readonly string FileName;
            public readonly string FileData;
            public readonly long ContactId;
            public readonly bool IsPublic;
            public readonly FileAssociation FileAssociation;
      
      public FileUpload(string fileName = default, string fileData = default, long contactId = default, bool isPublic = default, FileAssociation fileAssociation = default)
      {
                FileName = fileName;
                FileData = fileData;
                ContactId = contactId;
                IsPublic = isPublic;
                FileAssociation = fileAssociation;
        
      }

      public FileUpload Copy(string fileName = default, string fileData = default, long? contactId = default, bool isPublic = default, FileAssociation fileAssociation = default) => new FileUpload(
                  fileName:  fileName ?? FileName, 
                        fileData:  fileData ?? FileData, 
                        contactId:  contactId ?? ContactId, 
                        isPublic:  isPublic == default ? IsPublic : isPublic, 
                        fileAssociation:  fileAssociation == default ? FileAssociation : fileAssociation
            
      );
    }
}