//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum FileAssociation
  { 
    [EnumMember(Value = "CONTACT")]
    Contact,
    
    [EnumMember(Value = "USER")]
    User,
    
    [EnumMember(Value = "COMPANY")]
    Company
      }
}