//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum FileBoxType
  { 
    [EnumMember(Value = "Application")]
    Application,
    
    [EnumMember(Value = "Image")]
    Image,
    
    [EnumMember(Value = "Fax")]
    Fax,
    
    [EnumMember(Value = "Attachment")]
    Attachment,
    
    [EnumMember(Value = "Ticket")]
    Ticket,
    
    [EnumMember(Value = "Contact")]
    Contact,
    
    [EnumMember(Value = "DigitalProduct")]
    Digitalproduct,
    
    [EnumMember(Value = "Import")]
    Import,
    
    [EnumMember(Value = "Hidden")]
    Hidden,
    
    [EnumMember(Value = "WebForm")]
    Webform,
    
    [EnumMember(Value = "StyledCart")]
    Styledcart,
    
    [EnumMember(Value = "ReSampledImage")]
    Resampledimage,
    
    [EnumMember(Value = "TemplateThumbnail")]
    Templatethumbnail,
    
    [EnumMember(Value = "Funnel")]
    Funnel,
    
    [EnumMember(Value = "LogoThumbnail")]
    Logothumbnail
      }
}