//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class FullContact : Record<FullContact>
    {
            public readonly Lst<Address> Addresses;
            public readonly string Anniversary;
            public readonly string Birthday;
            public readonly CompanyReference Company;
            public readonly string ContactType;
            public readonly Lst<CustomFieldValue> CustomFields;
            public readonly string DateCreated;
            public readonly Lst<EmailAddress> EmailAddresses;
            public readonly bool EmailOptedIn;
            public readonly EmailStatus EmailStatus;
            public readonly string FamilyName;
            public readonly Lst<FaxNumber> FaxNumbers;
            public readonly string GivenName;
            public readonly long Id;
            public readonly string JobTitle;
            public readonly string LastUpdated;
            public readonly long LeadSourceId;
            public readonly string MiddleName;
            public readonly string Notes;
            public readonly string OptInReason;
            public readonly long OwnerId;
            public readonly Lst<PhoneNumber> PhoneNumbers;
            public readonly string PreferredLocale;
            public readonly string PreferredName;
            public readonly string Prefix;
            public readonly Lst<Relationship> Relationships;
            public readonly Lst<SocialAccount> SocialAccounts;
            public readonly SourceType SourceType;
            public readonly string SpouseName;
            public readonly string Suffix;
            public readonly Lst<long> TagIds;
            public readonly string TimeZone;
            public readonly string Website;
      
      public FullContact(Lst<Address> addresses = default, string anniversary = default, string birthday = default, CompanyReference company = default, string contactType = default, Lst<CustomFieldValue> customFields = default, string dateCreated = default, Lst<EmailAddress> emailAddresses = default, bool emailOptedIn = default, EmailStatus emailStatus = default, string familyName = default, Lst<FaxNumber> faxNumbers = default, string givenName = default, long id = default, string jobTitle = default, string lastUpdated = default, long leadSourceId = default, string middleName = default, string notes = default, string optInReason = default, long ownerId = default, Lst<PhoneNumber> phoneNumbers = default, string preferredLocale = default, string preferredName = default, string prefix = default, Lst<Relationship> relationships = default, Lst<SocialAccount> socialAccounts = default, SourceType sourceType = default, string spouseName = default, string suffix = default, Lst<long> tagIds = default, string timeZone = default, string website = default)
      {
                Addresses = addresses;
                Anniversary = anniversary;
                Birthday = birthday;
                Company = company;
                ContactType = contactType;
                CustomFields = customFields;
                DateCreated = dateCreated;
                EmailAddresses = emailAddresses;
                EmailOptedIn = emailOptedIn;
                EmailStatus = emailStatus;
                FamilyName = familyName;
                FaxNumbers = faxNumbers;
                GivenName = givenName;
                Id = id;
                JobTitle = jobTitle;
                LastUpdated = lastUpdated;
                LeadSourceId = leadSourceId;
                MiddleName = middleName;
                Notes = notes;
                OptInReason = optInReason;
                OwnerId = ownerId;
                PhoneNumbers = phoneNumbers;
                PreferredLocale = preferredLocale;
                PreferredName = preferredName;
                Prefix = prefix;
                Relationships = relationships;
                SocialAccounts = socialAccounts;
                SourceType = sourceType;
                SpouseName = spouseName;
                Suffix = suffix;
                TagIds = tagIds;
                TimeZone = timeZone;
                Website = website;
        
      }

      public FullContact Copy(Lst<Address> addresses = default, string anniversary = default, string birthday = default, CompanyReference company = default, string contactType = default, Lst<CustomFieldValue> customFields = default, string dateCreated = default, Lst<EmailAddress> emailAddresses = default, bool emailOptedIn = default, EmailStatus emailStatus = default, string familyName = default, Lst<FaxNumber> faxNumbers = default, string givenName = default, long? id = default, string jobTitle = default, string lastUpdated = default, long? leadSourceId = default, string middleName = default, string notes = default, string optInReason = default, long? ownerId = default, Lst<PhoneNumber> phoneNumbers = default, string preferredLocale = default, string preferredName = default, string prefix = default, Lst<Relationship> relationships = default, Lst<SocialAccount> socialAccounts = default, SourceType sourceType = default, string spouseName = default, string suffix = default, Lst<long> tagIds = default, string timeZone = default, string website = default) => new FullContact(
                  addresses:  addresses == default ? Addresses : addresses, 
                        anniversary:  anniversary ?? Anniversary, 
                        birthday:  birthday ?? Birthday, 
                        company:  company == default ? Company : company, 
                        contactType:  contactType ?? ContactType, 
                        customFields:  customFields == default ? CustomFields : customFields, 
                        dateCreated:  dateCreated ?? DateCreated, 
                        emailAddresses:  emailAddresses == default ? EmailAddresses : emailAddresses, 
                        emailOptedIn:  emailOptedIn == default ? EmailOptedIn : emailOptedIn, 
                        emailStatus:  emailStatus == default ? EmailStatus : emailStatus, 
                        familyName:  familyName ?? FamilyName, 
                        faxNumbers:  faxNumbers == default ? FaxNumbers : faxNumbers, 
                        givenName:  givenName ?? GivenName, 
                        id:  id ?? Id, 
                        jobTitle:  jobTitle ?? JobTitle, 
                        lastUpdated:  lastUpdated ?? LastUpdated, 
                        leadSourceId:  leadSourceId ?? LeadSourceId, 
                        middleName:  middleName ?? MiddleName, 
                        notes:  notes ?? Notes, 
                        optInReason:  optInReason ?? OptInReason, 
                        ownerId:  ownerId ?? OwnerId, 
                        phoneNumbers:  phoneNumbers == default ? PhoneNumbers : phoneNumbers, 
                        preferredLocale:  preferredLocale ?? PreferredLocale, 
                        preferredName:  preferredName ?? PreferredName, 
                        prefix:  prefix ?? Prefix, 
                        relationships:  relationships == default ? Relationships : relationships, 
                        socialAccounts:  socialAccounts == default ? SocialAccounts : socialAccounts, 
                        sourceType:  sourceType == default ? SourceType : sourceType, 
                        spouseName:  spouseName ?? SpouseName, 
                        suffix:  suffix ?? Suffix, 
                        tagIds:  tagIds == default ? TagIds : tagIds, 
                        timeZone:  timeZone ?? TimeZone, 
                        website:  website ?? Website
            
      );
    }
}