//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class HistoricalCounts : Record<HistoricalCounts>
    {
            public readonly int TwentyFourHours;
            public readonly int ThirtyDays;
      
      public HistoricalCounts(int twentyFourHours = default, int thirtyDays = default)
      {
                TwentyFourHours = twentyFourHours;
                ThirtyDays = thirtyDays;
        
      }

      public HistoricalCounts Copy(int? twentyFourHours = default, int? thirtyDays = default) => new HistoricalCounts(
                  twentyFourHours:  twentyFourHours ?? TwentyFourHours, 
                        thirtyDays:  thirtyDays ?? ThirtyDays
            
      );
    }
}