//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class InfusionTask : Record<InfusionTask>
    {
            public readonly bool Completed;
            public readonly string CompletionDate;
            public readonly BasicContact Contact;
            public readonly string CreationDate;
            public readonly string Description;
            public readonly string DueDate;
            public readonly string ModificationDate;
            public readonly int Priority;
            public readonly string Title;
            public readonly string Type;
            public readonly string Url;
            public readonly long UserId;
      
      public InfusionTask(bool completed = default, string completionDate = default, BasicContact contact = default, string creationDate = default, string description = default, string dueDate = default, string modificationDate = default, int priority = default, string title = default, string type = default, string url = default, long userId = default)
      {
                Completed = completed;
                CompletionDate = completionDate;
                Contact = contact;
                CreationDate = creationDate;
                Description = description;
                DueDate = dueDate;
                ModificationDate = modificationDate;
                Priority = priority;
                Title = title;
                Type = type;
                Url = url;
                UserId = userId;
        
      }

      public InfusionTask Copy(bool completed = default, string completionDate = default, BasicContact contact = default, string creationDate = default, string description = default, string dueDate = default, string modificationDate = default, int? priority = default, string title = default, string type = default, string url = default, long? userId = default) => new InfusionTask(
                  completed:  completed == default ? Completed : completed, 
                        completionDate:  completionDate ?? CompletionDate, 
                        contact:  contact == default ? Contact : contact, 
                        creationDate:  creationDate ?? CreationDate, 
                        description:  description ?? Description, 
                        dueDate:  dueDate ?? DueDate, 
                        modificationDate:  modificationDate ?? ModificationDate, 
                        priority:  priority ?? Priority, 
                        title:  title ?? Title, 
                        type:  type ?? Type, 
                        url:  url ?? Url, 
                        userId:  userId ?? UserId
            
      );
    }
}