//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum Key
  { 
    [EnumMember(Value = "SUCCESS")]
    Success,
    
    [EnumMember(Value = "DUPLICATE")]
    Duplicate,
    
    [EnumMember(Value = "CONTACT_NOT_FOUND")]
    Contactnotfound,
    
    [EnumMember(Value = "TAG_ID_NOT_FOUND")]
    Tagidnotfound,
    
    [EnumMember(Value = "FAILURE")]
    Failure,
    
    [EnumMember(Value = "NO_PERMISSION")]
    Nopermission
      }
}