//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class ObjectModel : Record<ObjectModel>
    {
            public readonly Lst<CustomFieldMetaData> CustomFields;
            public readonly Lst<string> OptionalProperties;
      
      public ObjectModel(Lst<CustomFieldMetaData> customFields = default, Lst<string> optionalProperties = default)
      {
                CustomFields = customFields;
                OptionalProperties = optionalProperties;
        
      }

      public ObjectModel Copy(Lst<CustomFieldMetaData> customFields = default, Lst<string> optionalProperties = default) => new ObjectModel(
                  customFields:  customFields == default ? CustomFields : customFields, 
                        optionalProperties:  optionalProperties == default ? OptionalProperties : optionalProperties
            
      );
    }
}