//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class OpportunityContact : Record<OpportunityContact>
    {
            public readonly string CompanyName;
            public readonly string Email;
            public readonly string FirstName;
            public readonly long Id;
            public readonly string JobTitle;
            public readonly string LastName;
            public readonly string PhoneNumber;
      
      public OpportunityContact(string companyName = default, string email = default, string firstName = default, long id = default, string jobTitle = default, string lastName = default, string phoneNumber = default)
      {
                CompanyName = companyName;
                Email = email;
                FirstName = firstName;
                Id = id;
                JobTitle = jobTitle;
                LastName = lastName;
                PhoneNumber = phoneNumber;
        
      }

      public OpportunityContact Copy(string companyName = default, string email = default, string firstName = default, long? id = default, string jobTitle = default, string lastName = default, string phoneNumber = default) => new OpportunityContact(
                  companyName:  companyName ?? CompanyName, 
                        email:  email ?? Email, 
                        firstName:  firstName ?? FirstName, 
                        id:  id ?? Id, 
                        jobTitle:  jobTitle ?? JobTitle, 
                        lastName:  lastName ?? LastName, 
                        phoneNumber:  phoneNumber ?? PhoneNumber
            
      );
    }
}