//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class OpportunityList : Record<OpportunityList>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly Lst<Opportunity> Opportunities;
            public readonly string Previous;
      
      public OpportunityList(int count = default, string next = default, Lst<Opportunity> opportunities = default, string previous = default)
      {
                Count = count;
                Next = next;
                Opportunities = opportunities;
                Previous = previous;
        
      }

      public OpportunityList Copy(int? count = default, string next = default, Lst<Opportunity> opportunities = default, string previous = default) => new OpportunityList(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        opportunities:  opportunities == default ? Opportunities : opportunities, 
                        previous:  previous ?? Previous
            
      );
    }
}