//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class OrderList : Record<OrderList>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly Lst<Order> Orders;
            public readonly string Previous;
      
      public OrderList(int count = default, string next = default, Lst<Order> orders = default, string previous = default)
      {
                Count = count;
                Next = next;
                Orders = orders;
                Previous = previous;
        
      }

      public OrderList Copy(int? count = default, string next = default, Lst<Order> orders = default, string previous = default) => new OrderList(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        orders:  orders == default ? Orders : orders, 
                        previous:  previous ?? Previous
            
      );
    }
}