//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class OrderItem : Record<OrderItem>
    {
            public readonly int Cost;
            public readonly string Description;
            public readonly int Discount;
            public readonly long Id;
            public readonly string Name;
            public readonly string Notes;
            public readonly int Price;
            public readonly SimpleProduct Product;
            public readonly int Quantity;
            public readonly string Type;
      
      public OrderItem(int cost = default, string description = default, int discount = default, long id = default, string name = default, string notes = default, int price = default, SimpleProduct product = default, int quantity = default, string type = default)
      {
                Cost = cost;
                Description = description;
                Discount = discount;
                Id = id;
                Name = name;
                Notes = notes;
                Price = price;
                Product = product;
                Quantity = quantity;
                Type = type;
        
      }

      public OrderItem Copy(int? cost = default, string description = default, int? discount = default, long? id = default, string name = default, string notes = default, int? price = default, SimpleProduct product = default, int? quantity = default, string type = default) => new OrderItem(
                  cost:  cost ?? Cost, 
                        description:  description ?? Description, 
                        discount:  discount ?? Discount, 
                        id:  id ?? Id, 
                        name:  name ?? Name, 
                        notes:  notes ?? Notes, 
                        price:  price ?? Price, 
                        product:  product == default ? Product : product, 
                        quantity:  quantity ?? Quantity, 
                        type:  type ?? Type
            
      );
    }
}