//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Order : Record<Order>
    {
            public readonly OrderContactDetails Contact;
            public readonly string CreationDate;
            public readonly long Id;
            public readonly long LeadAffiliateId;
            public readonly string ModificationDate;
            public readonly string OrderDate;
            public readonly Lst<OrderItem> OrderItems;
            public readonly bool Recurring;
            public readonly int RefundTotal;
            public readonly long SalesAffiliateId;
            public readonly ShippingInformation ShippingInformation;
            public readonly string Status;
            public readonly string Title;
            public readonly int Total;
            public readonly int TotalDue;
            public readonly int TotalPaid;
      
      public Order(OrderContactDetails contact = default, string creationDate = default, long id = default, long leadAffiliateId = default, string modificationDate = default, string orderDate = default, Lst<OrderItem> orderItems = default, bool recurring = default, int refundTotal = default, long salesAffiliateId = default, ShippingInformation shippingInformation = default, string status = default, string title = default, int total = default, int totalDue = default, int totalPaid = default)
      {
                Contact = contact;
                CreationDate = creationDate;
                Id = id;
                LeadAffiliateId = leadAffiliateId;
                ModificationDate = modificationDate;
                OrderDate = orderDate;
                OrderItems = orderItems;
                Recurring = recurring;
                RefundTotal = refundTotal;
                SalesAffiliateId = salesAffiliateId;
                ShippingInformation = shippingInformation;
                Status = status;
                Title = title;
                Total = total;
                TotalDue = totalDue;
                TotalPaid = totalPaid;
        
      }

      public Order Copy(OrderContactDetails contact = default, string creationDate = default, long? id = default, long? leadAffiliateId = default, string modificationDate = default, string orderDate = default, Lst<OrderItem> orderItems = default, bool recurring = default, int? refundTotal = default, long? salesAffiliateId = default, ShippingInformation shippingInformation = default, string status = default, string title = default, int? total = default, int? totalDue = default, int? totalPaid = default) => new Order(
                  contact:  contact == default ? Contact : contact, 
                        creationDate:  creationDate ?? CreationDate, 
                        id:  id ?? Id, 
                        leadAffiliateId:  leadAffiliateId ?? LeadAffiliateId, 
                        modificationDate:  modificationDate ?? ModificationDate, 
                        orderDate:  orderDate ?? OrderDate, 
                        orderItems:  orderItems == default ? OrderItems : orderItems, 
                        recurring:  recurring == default ? Recurring : recurring, 
                        refundTotal:  refundTotal ?? RefundTotal, 
                        salesAffiliateId:  salesAffiliateId ?? SalesAffiliateId, 
                        shippingInformation:  shippingInformation == default ? ShippingInformation : shippingInformation, 
                        status:  status ?? Status, 
                        title:  title ?? Title, 
                        total:  total ?? Total, 
                        totalDue:  totalDue ?? TotalDue, 
                        totalPaid:  totalPaid ?? TotalPaid
            
      );
    }
}