//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class ProductStatusList : Record<ProductStatusList>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
            public readonly Lst<ProductStatus> ProductStatuses;
            public readonly string SyncToken;
      
      public ProductStatusList(int count = default, string next = default, string previous = default, Lst<ProductStatus> productStatuses = default, string syncToken = default)
      {
                Count = count;
                Next = next;
                Previous = previous;
                ProductStatuses = productStatuses;
                SyncToken = syncToken;
        
      }

      public ProductStatusList Copy(int? count = default, string next = default, string previous = default, Lst<ProductStatus> productStatuses = default, string syncToken = default) => new ProductStatusList(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous, 
                        productStatuses:  productStatuses == default ? ProductStatuses : productStatuses, 
                        syncToken:  syncToken ?? SyncToken
            
      );
    }
}