//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Product : Record<Product>
    {
            public readonly long Id;
            public readonly string ProductDesc;
            public readonly string ProductName;
            public readonly Lst<ProductOption> ProductOptions;
            public readonly int ProductPrice;
            public readonly string ProductShortDesc;
            public readonly string Sku;
            public readonly int Status;
            public readonly long SubCategoryId;
            public readonly bool SubscriptionOnly;
            public readonly Lst<SubscriptionPlan> SubscriptionPlans;
            public readonly string Url;
      
      public Product(long id = default, string productDesc = default, string productName = default, Lst<ProductOption> productOptions = default, int productPrice = default, string productShortDesc = default, string sku = default, int status = default, long subCategoryId = default, bool subscriptionOnly = default, Lst<SubscriptionPlan> subscriptionPlans = default, string url = default)
      {
                Id = id;
                ProductDesc = productDesc;
                ProductName = productName;
                ProductOptions = productOptions;
                ProductPrice = productPrice;
                ProductShortDesc = productShortDesc;
                Sku = sku;
                Status = status;
                SubCategoryId = subCategoryId;
                SubscriptionOnly = subscriptionOnly;
                SubscriptionPlans = subscriptionPlans;
                Url = url;
        
      }

      public Product Copy(long? id = default, string productDesc = default, string productName = default, Lst<ProductOption> productOptions = default, int? productPrice = default, string productShortDesc = default, string sku = default, int? status = default, long? subCategoryId = default, bool subscriptionOnly = default, Lst<SubscriptionPlan> subscriptionPlans = default, string url = default) => new Product(
                  id:  id ?? Id, 
                        productDesc:  productDesc ?? ProductDesc, 
                        productName:  productName ?? ProductName, 
                        productOptions:  productOptions == default ? ProductOptions : productOptions, 
                        productPrice:  productPrice ?? ProductPrice, 
                        productShortDesc:  productShortDesc ?? ProductShortDesc, 
                        sku:  sku ?? Sku, 
                        status:  status ?? Status, 
                        subCategoryId:  subCategoryId ?? SubCategoryId, 
                        subscriptionOnly:  subscriptionOnly == default ? SubscriptionOnly : subscriptionOnly, 
                        subscriptionPlans:  subscriptionPlans == default ? SubscriptionPlans : subscriptionPlans, 
                        url:  url ?? Url
            
      );
    }
}