//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class ProductList : Record<ProductList>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
            public readonly Lst<Product> Products;
            public readonly string SyncToken;
      
      public ProductList(int count = default, string next = default, string previous = default, Lst<Product> products = default, string syncToken = default)
      {
                Count = count;
                Next = next;
                Previous = previous;
                Products = products;
                SyncToken = syncToken;
        
      }

      public ProductList Copy(int? count = default, string next = default, string previous = default, Lst<Product> products = default, string syncToken = default) => new ProductList(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous, 
                        products:  products == default ? Products : products, 
                        syncToken:  syncToken ?? SyncToken
            
      );
    }
}