//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Relationship : Record<Relationship>
    {
            public readonly long Id;
            public readonly long LinkedContactId;
            public readonly long RelationshipTypeId;
      
      public Relationship(long id = default, long linkedContactId = default, long relationshipTypeId = default)
      {
                Id = id;
                LinkedContactId = linkedContactId;
                RelationshipTypeId = relationshipTypeId;
        
      }

      public Relationship Copy(long? id = default, long? linkedContactId = default, long? relationshipTypeId = default) => new Relationship(
                  id:  id ?? Id, 
                        linkedContactId:  linkedContactId ?? LinkedContactId, 
                        relationshipTypeId:  relationshipTypeId ?? RelationshipTypeId
            
      );
    }
}