//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class RestHookRequest : Record<RestHookRequest>
    {
            public readonly string EventKey;
            public readonly string HookUrl;
      
      public RestHookRequest(string eventKey = default, string hookUrl = default)
      {
                EventKey = eventKey;
                HookUrl = hookUrl;
        
      }

      public RestHookRequest Copy(string eventKey = default, string hookUrl = default) => new RestHookRequest(
                  eventKey:  eventKey ?? EventKey, 
                        hookUrl:  hookUrl ?? HookUrl
            
      );
    }
}