//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SalesPipeline : Record<SalesPipeline>
    {
            public readonly bool EndStage;
            public readonly bool IsDefault;
            public readonly int StageCount;
            public readonly long StageId;
            public readonly string StageName;
            public readonly int StageOrder;
      
      public SalesPipeline(bool endStage = default, bool isDefault = default, int stageCount = default, long stageId = default, string stageName = default, int stageOrder = default)
      {
                EndStage = endStage;
                IsDefault = isDefault;
                StageCount = stageCount;
                StageId = stageId;
                StageName = stageName;
                StageOrder = stageOrder;
        
      }

      public SalesPipeline Copy(bool endStage = default, bool isDefault = default, int? stageCount = default, long? stageId = default, string stageName = default, int? stageOrder = default) => new SalesPipeline(
                  endStage:  endStage == default ? EndStage : endStage, 
                        isDefault:  isDefault == default ? IsDefault : isDefault, 
                        stageCount:  stageCount ?? StageCount, 
                        stageId:  stageId ?? StageId, 
                        stageName:  stageName ?? StageName, 
                        stageOrder:  stageOrder ?? StageOrder
            
      );
    }
}