//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SequencePath : Record<SequencePath>
    {
            public readonly long Id;
            public readonly Lst<Item> Items;
      
      public SequencePath(long id = default, Lst<Item> items = default)
      {
                Id = id;
                Items = items;
        
      }

      public SequencePath Copy(long? id = default, Lst<Item> items = default) => new SequencePath(
                  id:  id ?? Id, 
                        items:  items == default ? Items : items
            
      );
    }
}