//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Sequence : Record<Sequence>
    {
            public readonly int ActiveContactCount;
            public readonly int ActiveContactCountCompleted;
            public readonly HistoricalCounts HistoricalContactCount;
            public readonly long Id;
            public readonly string Name;
            public readonly Lst<SequencePath> Paths;
      
      public Sequence(int activeContactCount = default, int activeContactCountCompleted = default, HistoricalCounts historicalContactCount = default, long id = default, string name = default, Lst<SequencePath> paths = default)
      {
                ActiveContactCount = activeContactCount;
                ActiveContactCountCompleted = activeContactCountCompleted;
                HistoricalContactCount = historicalContactCount;
                Id = id;
                Name = name;
                Paths = paths;
        
      }

      public Sequence Copy(int? activeContactCount = default, int? activeContactCountCompleted = default, HistoricalCounts historicalContactCount = default, long? id = default, string name = default, Lst<SequencePath> paths = default) => new Sequence(
                  activeContactCount:  activeContactCount ?? ActiveContactCount, 
                        activeContactCountCompleted:  activeContactCountCompleted ?? ActiveContactCountCompleted, 
                        historicalContactCount:  historicalContactCount == default ? HistoricalContactCount : historicalContactCount, 
                        id:  id ?? Id, 
                        name:  name ?? Name, 
                        paths:  paths == default ? Paths : paths
            
      );
    }
}