//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SetOfIds : Record<SetOfIds>
    {
            public readonly Lst<long> Ids;
      
      public SetOfIds(Lst<long> ids = default)
      {
                Ids = ids;
        
      }

      public SetOfIds Copy(Lst<long> ids = default) => new SetOfIds(
                  ids:  ids == default ? Ids : ids
            
      );
    }
}