//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Setting : Record<Setting>
    {
            public readonly string Value;
      
      public Setting(string value = default)
      {
                Value = value;
        
      }

      public Setting Copy(string value = default) => new Setting(
                  value:  value ?? Value
            
      );
    }
}