//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SimpleProduct : Record<SimpleProduct>
    {
            public readonly string Description;
            public readonly long Id;
            public readonly string Name;
            public readonly bool Shippable;
            public readonly string Sku;
            public readonly bool Taxable;
      
      public SimpleProduct(string description = default, long id = default, string name = default, bool shippable = default, string sku = default, bool taxable = default)
      {
                Description = description;
                Id = id;
                Name = name;
                Shippable = shippable;
                Sku = sku;
                Taxable = taxable;
        
      }

      public SimpleProduct Copy(string description = default, long? id = default, string name = default, bool shippable = default, string sku = default, bool taxable = default) => new SimpleProduct(
                  description:  description ?? Description, 
                        id:  id ?? Id, 
                        name:  name ?? Name, 
                        shippable:  shippable == default ? Shippable : shippable, 
                        sku:  sku ?? Sku, 
                        taxable:  taxable == default ? Taxable : taxable
            
      );
    }
}