//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SimpleUser : Record<SimpleUser>
    {
            public readonly string FirstName;
            public readonly long Id;
            public readonly string LastName;
      
      public SimpleUser(string firstName = default, long id = default, string lastName = default)
      {
                FirstName = firstName;
                Id = id;
                LastName = lastName;
        
      }

      public SimpleUser Copy(string firstName = default, long? id = default, string lastName = default) => new SimpleUser(
                  firstName:  firstName ?? FirstName, 
                        id:  id ?? Id, 
                        lastName:  lastName ?? LastName
            
      );
    }
}