//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SocialAccount : Record<SocialAccount>
    {
            public readonly string Name;
            public readonly Type Type;
      
      public SocialAccount(string name = default, Type type = default)
      {
                Name = name;
                Type = type;
        
      }

      public SocialAccount Copy(string name = default, Type type = default) => new SocialAccount(
                  name:  name ?? Name, 
                        type:  type == default ? Type : type
            
      );
    }
}