//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum SourceType
  { 
    [EnumMember(Value = "WEBFORM")]
    Webform,
    
    [EnumMember(Value = "LANDINGPAGE")]
    Landingpage,
    
    [EnumMember(Value = "IMPORT")]
    Import,
    
    [EnumMember(Value = "MANUAL")]
    Manual,
    
    [EnumMember(Value = "API")]
    Api,
    
    [EnumMember(Value = "OTHER")]
    Other,
    
    [EnumMember(Value = "UNKNOWN")]
    Unknown
      }
}