//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class StackTraceElement : Record<StackTraceElement>
    {
            public readonly string ClassName;
            public readonly string FileName;
            public readonly int LineNumber;
            public readonly string MethodName;
            public readonly bool NativeMethod;
      
      public StackTraceElement(string className = default, string fileName = default, int lineNumber = default, string methodName = default, bool nativeMethod = default)
      {
                ClassName = className;
                FileName = fileName;
                LineNumber = lineNumber;
                MethodName = methodName;
                NativeMethod = nativeMethod;
        
      }

      public StackTraceElement Copy(string className = default, string fileName = default, int? lineNumber = default, string methodName = default, bool nativeMethod = default) => new StackTraceElement(
                  className:  className ?? ClassName, 
                        fileName:  fileName ?? FileName, 
                        lineNumber:  lineNumber ?? LineNumber, 
                        methodName:  methodName ?? MethodName, 
                        nativeMethod:  nativeMethod == default ? NativeMethod : nativeMethod
            
      );
    }
}