//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum Status
  { 
    [EnumMember(Value = "CREATED")]
    Created,
    
    [EnumMember(Value = "UPDATED")]
    Updated,
    
    [EnumMember(Value = "DELETED")]
    Deleted
      }
}