//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class SubscriptionPlan : Record<SubscriptionPlan>
    {
            public readonly bool Active;
            public readonly int Cycle;
            public readonly int Frequency;
            public readonly long Id;
            public readonly int NumberOfCycles;
            public readonly int PlanPrice;
            public readonly int SubscriptionPlanIndex;
            public readonly string SubscriptionPlanName;
            public readonly string Url;
      
      public SubscriptionPlan(bool active = default, int cycle = default, int frequency = default, long id = default, int numberOfCycles = default, int planPrice = default, int subscriptionPlanIndex = default, string subscriptionPlanName = default, string url = default)
      {
                Active = active;
                Cycle = cycle;
                Frequency = frequency;
                Id = id;
                NumberOfCycles = numberOfCycles;
                PlanPrice = planPrice;
                SubscriptionPlanIndex = subscriptionPlanIndex;
                SubscriptionPlanName = subscriptionPlanName;
                Url = url;
        
      }

      public SubscriptionPlan Copy(bool active = default, int? cycle = default, int? frequency = default, long? id = default, int? numberOfCycles = default, int? planPrice = default, int? subscriptionPlanIndex = default, string subscriptionPlanName = default, string url = default) => new SubscriptionPlan(
                  active:  active == default ? Active : active, 
                        cycle:  cycle ?? Cycle, 
                        frequency:  frequency ?? Frequency, 
                        id:  id ?? Id, 
                        numberOfCycles:  numberOfCycles ?? NumberOfCycles, 
                        planPrice:  planPrice ?? PlanPrice, 
                        subscriptionPlanIndex:  subscriptionPlanIndex ?? SubscriptionPlanIndex, 
                        subscriptionPlanName:  subscriptionPlanName ?? SubscriptionPlanName, 
                        url:  url ?? Url
            
      );
    }
}