//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Tag : Record<Tag>
    {
            public readonly TagCategory Category;
            public readonly string Description;
            public readonly long Id;
            public readonly string Name;
      
      public Tag(TagCategory category = default, string description = default, long id = default, string name = default)
      {
                Category = category;
                Description = description;
                Id = id;
                Name = name;
        
      }

      public Tag Copy(TagCategory category = default, string description = default, long? id = default, string name = default) => new Tag(
                  category:  category == default ? Category : category, 
                        description:  description ?? Description, 
                        id:  id ?? Id, 
                        name:  name ?? Name
            
      );
    }
}