//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class TaggedContact : Record<TaggedContact>
    {
            public readonly BasicContact Contact;
            public readonly string DateApplied;
      
      public TaggedContact(BasicContact contact = default, string dateApplied = default)
      {
                Contact = contact;
                DateApplied = dateApplied;
        
      }

      public TaggedContact Copy(BasicContact contact = default, string dateApplied = default) => new TaggedContact(
                  contact:  contact == default ? Contact : contact, 
                        dateApplied:  dateApplied ?? DateApplied
            
      );
    }
}