//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Tags : Record<Tags>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
            public readonly Lst<Tag> InnerTags;
      
      public Tags(int count = default, string next = default, string previous = default, Lst<Tag> innerTags = default)
      {
                Count = count;
                Next = next;
                Previous = previous;
                InnerTags = innerTags;
        
      }

      public Tags Copy(int? count = default, string next = default, string previous = default, Lst<Tag> innerTags = default) => new Tags(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous, 
                        innerTags:  innerTags == default ? InnerTags : innerTags
            
      );
    }
}