//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class TaskList : Record<TaskList>
    {
            public readonly int Count;
            public readonly string Next;
            public readonly string Previous;
            public readonly string SyncToken;
            public readonly Lst<InfusionTask> Tasks;
      
      public TaskList(int count = default, string next = default, string previous = default, string syncToken = default, Lst<InfusionTask> tasks = default)
      {
                Count = count;
                Next = next;
                Previous = previous;
                SyncToken = syncToken;
                Tasks = tasks;
        
      }

      public TaskList Copy(int? count = default, string next = default, string previous = default, string syncToken = default, Lst<InfusionTask> tasks = default) => new TaskList(
                  count:  count ?? Count, 
                        next:  next ?? Next, 
                        previous:  previous ?? Previous, 
                        syncToken:  syncToken ?? SyncToken, 
                        tasks:  tasks == default ? Tasks : tasks
            
      );
    }
}