//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class Throwable : Record<Throwable>
    {
            public readonly Throwable Cause;
            public readonly string LocalizedMessage;
            public readonly string Message;
            public readonly Lst<StackTraceElement> StackTrace;
            public readonly Lst<Throwable> Suppressed;
      
      public Throwable(Throwable cause = default, string localizedMessage = default, string message = default, Lst<StackTraceElement> stackTrace = default, Lst<Throwable> suppressed = default)
      {
                Cause = cause;
                LocalizedMessage = localizedMessage;
                Message = message;
                StackTrace = stackTrace;
                Suppressed = suppressed;
        
      }

      public Throwable Copy(Throwable cause = default, string localizedMessage = default, string message = default, Lst<StackTraceElement> stackTrace = default, Lst<Throwable> suppressed = default) => new Throwable(
                  cause:  cause == default ? Cause : cause, 
                        localizedMessage:  localizedMessage ?? LocalizedMessage, 
                        message:  message ?? Message, 
                        stackTrace:  stackTrace == default ? StackTrace : stackTrace, 
                        suppressed:  suppressed == default ? Suppressed : suppressed
            
      );
    }
}