//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System.Runtime.Serialization;

namespace Infusion.Model
{ 
  public enum Type
  { 
    [EnumMember(Value = "Facebook")]
    Facebook,
    
    [EnumMember(Value = "Twitter")]
    Twitter,
    
    [EnumMember(Value = "LinkedIn")]
    Linkedin
      }
}