//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using LanguageExt;

namespace Infusion.Model
{
    public class UserInfoDTO : Record<UserInfoDTO>
    {
            public readonly string Email;
            public readonly string FamilyName;
            public readonly string GivenName;
            public readonly long GlobalUserId;
            public readonly string InfusionsoftId;
            public readonly string MiddleName;
            public readonly string PreferredName;
            public readonly string Sub;
      
      public UserInfoDTO(string email = default, string familyName = default, string givenName = default, long globalUserId = default, string infusionsoftId = default, string middleName = default, string preferredName = default, string sub = default)
      {
                Email = email;
                FamilyName = familyName;
                GivenName = givenName;
                GlobalUserId = globalUserId;
                InfusionsoftId = infusionsoftId;
                MiddleName = middleName;
                PreferredName = preferredName;
                Sub = sub;
        
      }

      public UserInfoDTO Copy(string email = default, string familyName = default, string givenName = default, long? globalUserId = default, string infusionsoftId = default, string middleName = default, string preferredName = default, string sub = default) => new UserInfoDTO(
                  email:  email ?? Email, 
                        familyName:  familyName ?? FamilyName, 
                        givenName:  givenName ?? GivenName, 
                        globalUserId:  globalUserId ?? GlobalUserId, 
                        infusionsoftId:  infusionsoftId ?? InfusionsoftId, 
                        middleName:  middleName ?? MiddleName, 
                        preferredName:  preferredName ?? PreferredName, 
                        sub:  sub ?? Sub
            
      );
    }
}