//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class AddContactToCampaignSequence<A> : InfusionOp<A>
  {
    public readonly Func<Unit, InfusionOp<A>> Next;
      public readonly long? ContactId;
      public readonly long? SequenceId;
      public readonly long? CampaignId;
    
    public AddContactToCampaignSequence(Func<Unit, InfusionOp<A>> next, long? contactId, long? sequenceId, long? campaignId)
    {
            ContactId = contactId;
            SequenceId = sequenceId;
            CampaignId = campaignId;
          }
  }
}