//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class CreateCreditCard<A> : InfusionOp<A>
  {
    public readonly Func<Unit, InfusionOp<A>> Next;
      public readonly long? ContactId;
      public readonly CreditCard CreditCard;
    
    public CreateCreditCard(Func<Unit, InfusionOp<A>> next, long? contactId, CreditCard creditCard)
    {
            ContactId = contactId;
            CreditCard = creditCard;
          }
  }
}