//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetAppointment<A> : InfusionOp<A>
  {
    public readonly Func<Appointment, InfusionOp<A>> Next;
      public readonly long? AppointmentId;
    
    public GetAppointment(Func<Appointment, InfusionOp<A>> next, long? appointmentId)
    {
            AppointmentId = appointmentId;
          }
  }
}