//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetApplicationEnabled<A> : InfusionOp<A>
  {
    public readonly Func<Setting, InfusionOp<A>> Next;
    
    public GetApplicationEnabled(Func<Setting, InfusionOp<A>> next)
    {
          }
  }
}