//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetAccountProfile<A> : InfusionOp<A>
  {
    public readonly Func<AccountProfile, InfusionOp<A>> Next;
    
    public GetAccountProfile(Func<AccountProfile, InfusionOp<A>> next)
    {
          }
  }
}