//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetEmail<A> : InfusionOp<A>
  {
    public readonly Func<EmailSentQueryResultWithContent, InfusionOp<A>> Next;
      public readonly long? Id;
    
    public GetEmail(Func<EmailSentQueryResultWithContent, InfusionOp<A>> next, long? id)
    {
            Id = id;
          }
  }
}