//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetTask<A> : InfusionOp<A>
  {
    public readonly Func<InfusionTask, InfusionOp<A>> Next;
      public readonly string TaskId;
    
    public GetTask(Func<InfusionTask, InfusionOp<A>> next, string taskId)
    {
            TaskId = taskId;
          }
  }
}