//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetTag<A> : InfusionOp<A>
  {
    public readonly Func<Tag, InfusionOp<A>> Next;
      public readonly long? Id;
    
    public GetTag(Func<Tag, InfusionOp<A>> next, long? id)
    {
            Id = id;
          }
  }
}