//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetTransaction<A> : InfusionOp<A>
  {
    public readonly Func<Transaction, InfusionOp<A>> Next;
      public readonly long? TransactionId;
    
    public GetTransaction(Func<Transaction, InfusionOp<A>> next, long? transactionId)
    {
            TransactionId = transactionId;
          }
  }
}