//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class GetUserInfo<A> : InfusionOp<A>
  {
    public readonly Func<UserInfoDTO, InfusionOp<A>> Next;
    
    public GetUserInfo(Func<UserInfoDTO, InfusionOp<A>> next)
    {
          }
  }
}