//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListAppliedTags<A> : InfusionOp<A>
  {
    public readonly Func<ContactTagList, InfusionOp<A>> Next;
      public readonly long? ContactId;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListAppliedTags(Func<ContactTagList, InfusionOp<A>> next, long? contactId, int? offset, int? limit)
    {
            ContactId = contactId;
            Offset = offset;
            Limit = limit;
          }
  }
}