//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListTasks<A> : InfusionOp<A>
  {
    public readonly Func<TaskList, InfusionOp<A>> Next;
      public readonly string Order;
      public readonly int? Offset;
      public readonly int? Limit;
      public readonly bool Completed;
      public readonly string Until;
      public readonly string Since;
      public readonly long? UserId;
      public readonly bool HasDueDate;
      public readonly long? ContactId;
    
    public ListTasks(Func<TaskList, InfusionOp<A>> next, string order, int? offset, int? limit, bool completed, string until, string since, long? userId, bool hasDueDate, long? contactId)
    {
            Order = order;
            Offset = offset;
            Limit = limit;
            Completed = completed;
            Until = until;
            Since = since;
            UserId = userId;
            HasDueDate = hasDueDate;
            ContactId = contactId;
          }
  }
}