//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListProducts<A> : InfusionOp<A>
  {
    public readonly Func<ProductList, InfusionOp<A>> Next;
      public readonly bool Active;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListProducts(Func<ProductList, InfusionOp<A>> next, bool active, int? offset, int? limit)
    {
            Active = active;
            Offset = offset;
            Limit = limit;
          }
  }
}