//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListStoredHookSubscriptions<A> : InfusionOp<A>
  {
    public readonly Func<Unit, InfusionOp<A>> Next;
    
    public ListStoredHookSubscriptions(Func<Unit, InfusionOp<A>> next)
    {
          }
  }
}