//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListProductsFromSyncToken<A> : InfusionOp<A>
  {
    public readonly Func<ProductStatusList, InfusionOp<A>> Next;
      public readonly int? Offset;
      public readonly int? Limit;
      public readonly string SyncToken;
    
    public ListProductsFromSyncToken(Func<ProductStatusList, InfusionOp<A>> next, int? offset, int? limit, string syncToken)
    {
            Offset = offset;
            Limit = limit;
            SyncToken = syncToken;
          }
  }
}