//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListTransactionsForOrder<A> : InfusionOp<A>
  {
    public readonly Func<TransactionList, InfusionOp<A>> Next;
      public readonly long? OrderId;
      public readonly long? ContactId;
      public readonly int? Offset;
      public readonly int? Limit;
      public readonly string Until;
      public readonly string Since;
    
    public ListTransactionsForOrder(Func<TransactionList, InfusionOp<A>> next, long? orderId, long? contactId, int? offset, int? limit, string until, string since)
    {
            OrderId = orderId;
            ContactId = contactId;
            Offset = offset;
            Limit = limit;
            Until = until;
            Since = since;
          }
  }
}