//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListAppointments<A> : InfusionOp<A>
  {
    public readonly Func<AppointmentList, InfusionOp<A>> Next;
      public readonly long? ContactId;
      public readonly int? Offset;
      public readonly int? Limit;
      public readonly string Until;
      public readonly string Since;
    
    public ListAppointments(Func<AppointmentList, InfusionOp<A>> next, long? contactId, int? offset, int? limit, string until, string since)
    {
            ContactId = contactId;
            Offset = offset;
            Limit = limit;
            Until = until;
            Since = since;
          }
  }
}