//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListOpportunities<A> : InfusionOp<A>
  {
    public readonly Func<OpportunityList, InfusionOp<A>> Next;
      public readonly string Order;
      public readonly string SearchTerm;
      public readonly long? StageId;
      public readonly long? UserId;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListOpportunities(Func<OpportunityList, InfusionOp<A>> next, string order, string searchTerm, long? stageId, long? userId, int? offset, int? limit)
    {
            Order = order;
            SearchTerm = searchTerm;
            StageId = stageId;
            UserId = userId;
            Offset = offset;
            Limit = limit;
          }
  }
}