//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListContactsForTagId<A> : InfusionOp<A>
  {
    public readonly Func<TaggedContactList, InfusionOp<A>> Next;
      public readonly long? TagId;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListContactsForTagId(Func<TaggedContactList, InfusionOp<A>> next, long? tagId, int? offset, int? limit)
    {
            TagId = tagId;
            Offset = offset;
            Limit = limit;
          }
  }
}