//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListEmailsForContact<A> : InfusionOp<A>
  {
    public readonly Func<EmailSentQueryResultList, InfusionOp<A>> Next;
      public readonly long? ContactId;
      public readonly string Email;
      public readonly long? ContactId2;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListEmailsForContact(Func<EmailSentQueryResultList, InfusionOp<A>> next, long? contactId, string email, long? contactId2, int? offset, int? limit)
    {
            ContactId = contactId;
            Email = email;
            ContactId2 = contactId2;
            Offset = offset;
            Limit = limit;
          }
  }
}