//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListCompanies<A> : InfusionOp<A>
  {
    public readonly Func<CompanyList, InfusionOp<A>> Next;
      public readonly Lst<string> OptionalProperties;
      public readonly string OrderDirection;
      public readonly string Order;
      public readonly string CompanyName;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListCompanies(Func<CompanyList, InfusionOp<A>> next, Lst<string> optionalProperties, string orderDirection, string order, string companyName, int? offset, int? limit)
    {
            OptionalProperties = optionalProperties;
            OrderDirection = orderDirection;
            Order = order;
            CompanyName = companyName;
            Offset = offset;
            Limit = limit;
          }
  }
}