//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListOpportunityStagePipelines<A> : InfusionOp<A>
  {
    public readonly Func<Unit, InfusionOp<A>> Next;
    
    public ListOpportunityStagePipelines(Func<Unit, InfusionOp<A>> next)
    {
          }
  }
}