//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListContacts<A> : InfusionOp<A>
  {
    public readonly Func<ContactList, InfusionOp<A>> Next;
      public readonly string OrderDirection;
      public readonly string Order;
      public readonly string FamilyName;
      public readonly string GivenName;
      public readonly string Email;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListContacts(Func<ContactList, InfusionOp<A>> next, string orderDirection, string order, string familyName, string givenName, string email, int? offset, int? limit)
    {
            OrderDirection = orderDirection;
            Order = order;
            FamilyName = familyName;
            GivenName = givenName;
            Email = email;
            Offset = offset;
            Limit = limit;
          }
  }
}