//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListCampaigns<A> : InfusionOp<A>
  {
    public readonly Func<CampaignList, InfusionOp<A>> Next;
      public readonly string OrderDirection;
      public readonly string Order;
      public readonly string SearchText;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListCampaigns(Func<CampaignList, InfusionOp<A>> next, string orderDirection, string order, string searchText, int? offset, int? limit)
    {
            OrderDirection = orderDirection;
            Order = order;
            SearchText = searchText;
            Offset = offset;
            Limit = limit;
          }
  }
}