//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class ListFiles<A> : InfusionOp<A>
  {
    public readonly Func<FileList, InfusionOp<A>> Next;
      public readonly string Name;
      public readonly string Type;
      public readonly string Permission;
      public readonly string Viewable;
      public readonly int? Offset;
      public readonly int? Limit;
    
    public ListFiles(Func<FileList, InfusionOp<A>> next, string name, string type, string permission, string viewable, int? offset, int? limit)
    {
            Name = name;
            Type = type;
            Permission = permission;
            Viewable = viewable;
            Offset = offset;
            Limit = limit;
          }
  }
}