//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class RemoveTagsFromContact<A> : InfusionOp<A>
  {
    public readonly Func<Unit, InfusionOp<A>> Next;
      public readonly long? TagId;
      public readonly long? ContactId;
    
    public RemoveTagsFromContact(Func<Unit, InfusionOp<A>> next, long? tagId, long? contactId)
    {
            TagId = tagId;
            ContactId = contactId;
          }
  }
}