//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class RetrieveSubscriptionModel<A> : InfusionOp<A>
  {
    public readonly Func<ObjectModel, InfusionOp<A>> Next;
    
    public RetrieveSubscriptionModel(Func<ObjectModel, InfusionOp<A>> next)
    {
          }
  }
}