//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class RetrieveAHookSubscription<A> : InfusionOp<A>
  {
    public readonly Func<RestHook, InfusionOp<A>> Next;
      public readonly string Key;
    
    public RetrieveAHookSubscription(Func<RestHook, InfusionOp<A>> next, string key)
    {
            Key = key;
          }
  }
}