//----------------------
// <auto-generated>
// </auto-generated>
//----------------------
using System;
using LanguageExt;
using Infusion.Model;

namespace Infusion.Ops
{
  internal class VerifyAHookSubscription<A> : InfusionOp<A>
  {
    public readonly Func<RestHook, InfusionOp<A>> Next;
      public readonly string Key;
    
    public VerifyAHookSubscription(Func<RestHook, InfusionOp<A>> next, string key)
    {
            Key = key;
          }
  }
}